python county.py
python newzipcode.py
python covid-tracking.py
#python state.py
python state_rank.py
python national.py
python regional_hospitalization.py
python regional_charts.py
python state_charts.py
python zip_charts.py
python national_charts.py
